# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\P\MEPApp\Qt\ECGViewerQt\Resources\EMGViewerGUI.ui'
#
# Created: Fri Jul 10 14:59:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1062, 897)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSave = QtGui.QMenu(self.menuFile)
        self.menuSave.setObjectName(_fromUtf8("menuSave"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pas_response_delay_spinbox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pas_response_delay_spinbox.setSingleStep(0.01)
        self.pas_response_delay_spinbox.setProperty("value", 0.02)
        self.pas_response_delay_spinbox.setObjectName(_fromUtf8("pas_response_delay_spinbox"))
        self.gridLayout_6.addWidget(self.pas_response_delay_spinbox, 1, 1, 1, 1)
        self.pas_response_window_spinbox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pas_response_window_spinbox.setSingleStep(0.01)
        self.pas_response_window_spinbox.setProperty("value", 0.08)
        self.pas_response_window_spinbox.setObjectName(_fromUtf8("pas_response_window_spinbox"))
        self.gridLayout_6.addWidget(self.pas_response_window_spinbox, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.pas_trigger_threshold_spinbox = QtGui.QDoubleSpinBox(self.groupBox)
        self.pas_trigger_threshold_spinbox.setSingleStep(0.1)
        self.pas_trigger_threshold_spinbox.setProperty("value", 1.0)
        self.pas_trigger_threshold_spinbox.setObjectName(_fromUtf8("pas_trigger_threshold_spinbox"))
        self.gridLayout_6.addWidget(self.pas_trigger_threshold_spinbox, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.csp_csp_threshold_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.csp_csp_threshold_spinbox.setSingleStep(0.01)
        self.csp_csp_threshold_spinbox.setProperty("value", 0.1)
        self.csp_csp_threshold_spinbox.setObjectName(_fromUtf8("csp_csp_threshold_spinbox"))
        self.gridLayout_4.addWidget(self.csp_csp_threshold_spinbox, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.csp_trigger_threshold_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.csp_trigger_threshold_spinbox.setSingleStep(0.1)
        self.csp_trigger_threshold_spinbox.setProperty("value", 1.0)
        self.csp_trigger_threshold_spinbox.setObjectName(_fromUtf8("csp_trigger_threshold_spinbox"))
        self.gridLayout_4.addWidget(self.csp_trigger_threshold_spinbox, 1, 1, 1, 1)
        self.csp_response_delay_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.csp_response_delay_spinbox.setSingleStep(0.1)
        self.csp_response_delay_spinbox.setObjectName(_fromUtf8("csp_response_delay_spinbox"))
        self.gridLayout_4.addWidget(self.csp_response_delay_spinbox, 2, 1, 1, 1)
        self.csp_response_window_spinbox = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.csp_response_window_spinbox.setSingleStep(0.1)
        self.csp_response_window_spinbox.setProperty("value", 1.0)
        self.csp_response_window_spinbox.setObjectName(_fromUtf8("csp_response_window_spinbox"))
        self.gridLayout_4.addWidget(self.csp_response_window_spinbox, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.csp_duration_vs_time_checkbox = QtGui.QCheckBox(self.groupBox_2)
        self.csp_duration_vs_time_checkbox.setObjectName(_fromUtf8("csp_duration_vs_time_checkbox"))
        self.gridLayout_4.addWidget(self.csp_duration_vs_time_checkbox, 4, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionCSV = QtGui.QAction(MainWindow)
        self.actionCSV.setObjectName(_fromUtf8("actionCSV"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAnnotate_Min_Max = QtGui.QAction(MainWindow)
        self.actionAnnotate_Min_Max.setObjectName(_fromUtf8("actionAnnotate_Min_Max"))
        self.actionClear_Scene = QtGui.QAction(MainWindow)
        self.actionClear_Scene.setObjectName(_fromUtf8("actionClear_Scene"))
        self.actionManually_Add_Trigger = QtGui.QAction(MainWindow)
        self.actionManually_Add_Trigger.setObjectName(_fromUtf8("actionManually_Add_Trigger"))
        self.menuSave.addAction(self.actionCSV)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuActions.addAction(self.actionAnnotate_Min_Max)
        self.menuActions.addAction(self.actionClear_Scene)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionManually_Add_Trigger)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSave.setTitle(_translate("MainWindow", "Save", None))
        self.menuActions.setTitle(_translate("MainWindow", "Actions", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.label_2.setText(_translate("MainWindow", "Current File:", None))
        self.label.setText(_translate("MainWindow", "Mode: ", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "PAS", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Paired Pulse", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Cortical Silent Period", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Load a .smr file.", None))
        self.groupBox.setTitle(_translate("MainWindow", "PAS Parameters", None))
        self.label_6.setText(_translate("MainWindow", "Trigger Threshold:", None))
        self.label_7.setText(_translate("MainWindow", "Response Window (s):", None))
        self.label_5.setText(_translate("MainWindow", "Response Delay (s):", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cortical Silent Period Parameters", None))
        self.label_14.setText(_translate("MainWindow", "CSP Threshold", None))
        self.label_12.setText(_translate("MainWindow", "Trigger Threshold:", None))
        self.label_4.setText(_translate("MainWindow", "Response Delay (s):", None))
        self.label_13.setText(_translate("MainWindow", "Response Window (s):", None))
        self.csp_duration_vs_time_checkbox.setText(_translate("MainWindow", "Show CSP Duration vs Time Plot", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionCSV.setText(_translate("MainWindow", "CSV", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAnnotate_Min_Max.setText(_translate("MainWindow", "Annotate Min/Max", None))
        self.actionClear_Scene.setText(_translate("MainWindow", "Clear Scene", None))
        self.actionManually_Add_Trigger.setText(_translate("MainWindow", "Manually Add Trigger", None))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

